#!/bin/sh
# Stamp the version into snapshot/_build_info.py before packaging.
set -e
version="${1:?usage: tools/release.sh VERSION}"
cat > "$(dirname "$0")/../snapshot/_build_info.py" <<PY
# @generated by tools/release.sh -- do not edit
VERSION = "$version"
BUILT = "$(date +%Y-%m-%d)"
PY
echo "stamped $version"
