"""Random cases for v2.2, tagged by which packignore rules they exercise.

v2.2 cases also give some files a first line containing "@generated" (or the
marker on a later line, as a decoy) and some files the executable bit, since
H5/H6 depend on those properties rather than the path.

A case is a file tree plus .packignore files. As in v1, the generator only
decides what to try; the answer comes from the reference implementation.

Tagging: a case exercises rule R if switching R off (packignore.ABLATIONS)
changes the answer. That is exact, not a guess from the pattern text, which
was v1's weakness (most v1 cases matched every feature).
"""

import os
import random
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "reference"))
import packignore  # noqa: E402

NAMES = ["a", "b", "c", "ab", "ba", "keep", "build", "x"]
EXTS = ["", ".log", ".tmp", ".txt"]
SPECIAL = ["#notes", "; logs", "#a.log"]


def gen_tree(rng, max_depth=6):
    files, dirs = [], []

    def walk(prefix, depth):
        used = set()
        for _ in range(rng.randint(1, 3)):
            n = rng.choice(SPECIAL) if rng.random() < 0.06 else rng.choice(NAMES) + rng.choice(EXTS)
            if n not in used:
                used.add(n)
                files.append(prefix + n)
        if depth >= max_depth:
            return
        # Keep some trees deep so the ** depth limit (H2) gets exercised.
        k = rng.choice([1, 1, 2]) if depth < 2 else rng.choice([0, 1, 1])
        for _ in range(k):
            n = rng.choice(NAMES)
            if n not in used:
                used.add(n)
                dirs.append(prefix + n)
                walk(prefix + n + "/", depth + 1)

    walk("", 0)
    return files, dirs


def gen_line(rng, base, files, dirs):
    under = [p[len(base):] for p in files + dirs if p.startswith(base) and p != base.rstrip("/")]
    rel = rng.choice(under) if under else "a"
    name = rel.split("/")[-1]
    stem, _, ext = name.partition(".")
    r = rng.random()
    if r < 0.12:
        line = name
    elif r < 0.22:
        line = "*." + (ext or "log")
    elif r < 0.30:
        line = "*.{" + ",".join(rng.sample(["log", "tmp", "txt"], 2)) + "}"
    elif r < 0.36:
        line = "{" + ",".join(rng.sample(NAMES, 2)) + "}" + (("." + ext) if ext else "*")
    elif r < 0.48:
        line = "**/" + name
    elif r < 0.56:
        parts = rel.split("/")
        line = parts[0] + "/**/" + parts[-1] if len(parts) > 1 else "**/" + name
    elif r < 0.66:
        line = rel                                   # anchored if it has a '/'
    elif r < 0.72:
        line = "/" + name
    elif r < 0.82:
        line = rel.split("/")[0] + "/"               # directory pattern
    elif r < 0.88:
        line = stem + "*" if stem else "*"
    elif r < 0.93:
        line = "; " + rng.choice(["old", "logs", "build output"])
    else:
        line = "#" + rng.choice(["notes", "a.log", "a"])
    if rng.random() < 0.3 and not line.startswith((";", "#")):
        line = "!" + line
    return line


GEN_FIRST_LINES = ["# @generated by tools/release.sh", "// @generated", "/* @generated */",
                   "<!-- @generated -->"]


def gen_case(seed):
    rng = random.Random(seed)
    files, dirs = gen_tree(rng)
    contents, executable = {}, []
    for f in files:
        r = rng.random()
        if r < 0.10:
            contents[f] = rng.choice(GEN_FIRST_LINES) + "\nx = 1\n"
        elif r < 0.14:
            contents[f] = "x = 1\n# @generated\n"            # decoy: not the first line
        if rng.random() < 0.10:
            executable.append(f)
    bases = [""] + [d + "/" for d in dirs if rng.random() < 0.3]
    for b in bases:
        lines = [gen_line(rng, b, files, dirs) for _ in range(rng.randint(1, 6))]
        contents[b + packignore.IGNORE_FILE] = "\n".join(lines) + "\n"
    return {"files": sorted(files + [b + packignore.IGNORE_FILE for b in bases]),
            "contents": contents, "executable": sorted(executable)}


def materialize(case, root):
    os.makedirs(root, exist_ok=True)
    for rel in case["files"]:
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", newline="") as f:
            f.write(case["contents"].get(rel, "x\n"))
        os.chmod(path, 0o755 if rel in case.get("executable", ()) else 0o644)


def answer(case, rules=packignore.TRUE):
    with tempfile.TemporaryDirectory() as tmp:
        materialize(case, tmp)
        return packignore.ignored_files(tmp, rules)


def tag(case):
    truth = answer(case)
    tags = [name for name, rules in packignore.ABLATIONS.items() if answer(case, rules) != truth]
    return truth, tags
